spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-activity
      database: fitness-activity

server:
  port: 8082

eureka:
  client:
    serviceUrl: #locates eureka server
      defaultZone: http://localhost:8761/eureka/