spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver: # OAuth2 resource server that validates tokens but doesn't issue them
        jwt: # jwt is token format
          # points to JSON web key set endpoints where gateway can fetch public keys to verify JWT signatures
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  cloud:
    gateway:
      routes: # checks if req has path of /api/users, redirects to USER-SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: activity-service # unique identifier for this specific route
          uri: lb://ACTIVITY-SERVICE # target destination using load balancer to route to USER-SERVICE registered in Eureka
          predicates: #conditions that must be met for this route to be used
            - Path=/api/activities/** # if requests starts with /api/users -> USER-SERVICE/api/users

        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/api/recommendations/**

server:
  port: 8080

eureka:
  client:
    serviceUrl: #locates eureka server
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id:
